Fix Timezone
Laravel-Backpack/BackupManager pull request #128
Opened 2024-06-21 16:26 UTC by MarioVillani

Correct hours and minutes are shown using user's timezone.

## WHY

### BEFORE - What was wrong? What was happening before this PR?

isoFormat did not take user's timezone into account.

### AFTER - What is happening after this PR?

Correct hours and minutes are shown.

## HOW

### How did you achieve that, in technical terms?

Adding date_default_timezone_get() as second parameter for createFromTimeStamp() function.

### Is it a breaking change or non-breaking change?

Non-breaking

### How can we test the before & after?

Check if hours and minutes are shown correctly.

2024-06-22 10:49 UTC, MarioVillani commented
EDIT: Added Italian Language strings.

2024-06-24 09:56 UTC, pxpm requested changes
Hey @MarioVillani thanks again for another PR. 

My only comment here is the same I did in your other PR: https://github.com/Laravel-Backpack/LogManager/pull/69#pullrequestreview-2135269422

Let me know what you think 🙏

2024-06-24 09:56 UTC, pxpm commented on src/app/Http/Controllers/BackupController.php
> +                        'lastModified' => Carbon::createFromTimeStamp($disk->lastModified($file), date_default_timezone_get())->isoFormat('DD MMMM YYYY, HH:mm'),
```suggestion
                        'lastModified' => Carbon::createFromTimeStamp($disk->lastModified($file), config('app.timezone'))->isoFormat('DD MMMM YYYY, HH:mm'),
```

2024-06-24 09:58 UTC, MarioVillani commented
I was editing this after your suggestion for LogManager, you anticipated me :)
You may proceed with the merge if everything else is ok. Thanks!

2024-06-24 10:02 UTC, merged